In [2]:
import pandas as pd
import numpy as np
import re
from sklearn.impute import SimpleImputer

In [3]:
pd.read_csv('datadump_s5-000.csv')

,dateid,platform,gamemode,mapname,matchid,roundnumber,objectivelocation,winrole,endroundreason,roundduration,...,primarygrip,primaryunderbarrel,primarybarrel,secondaryweapon,secondaryweapontype,secondarysight,secondarygrip,secondaryunderbarrel,secondarybarrel,secondarygadget
0,20170212,PC,HOSTAGE,CLUB_HOUSE,1522380841,1,STRIP_CLUB,Defender,AttackersKilledHostage,124,...,Vertical,None,Compensator,5.7_USG,Pistols,None,None,None,None,IMPACT_GRENADE
1,20170212,PC,HOSTAGE,CLUB_HOUSE,1522380841,4,CHURCH,Defender,AttackersEliminated,217,...,Vertical,Laser,Suppressor,P12,Pistols,None,None,Laser,Suppressor,DEPLOYABLE_SHIELD
2,20170212,PC,HOSTAGE,CLUB_HOUSE,1522380841,3,CHURCH,Defender,AttackersEliminated,160,...,None,None,None,MK1_9mm,Pistols,None,None,None,None,DEPLOYABLE_SHIELD
3,20170212,PC,HOSTAGE,CLUB_HOUSE,1522380841,4,CHURCH,Defender,AttackersEliminated,217,...,None,None,MuzzleBrake,PRB92,Pistols,None,None,None,None,IMPACT_GRENADE
4,20170212,PC,HOSTAGE,CLUB_HOUSE,1522380841,6,BEDROOM,Attacker,DefendersEliminated,143,...,Vertical,Laser,Suppressor,P12,Pistols,None,None,Laser,Suppressor,DEPLOYABLE_SHIELD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3999995,20170221,PS4,HOSTAGE,BANK,1368316041,6,STAFF_ROOM,Defender,AttackersEliminated,158,...,Vertical,None,None,BEARING_9,Submachine_Guns,RedDot,None,None,None,CLAYMORE
3999996,20170221,PS4,HOSTAGE,BANK,1368316041,2,VAULT,Attacker,DefendersEliminated,170,...,Vertical,None,None,BEARING_9,Submachine_Guns,RedDot,None,None,None,CLAYMORE
3999997,20170221,PS4,HOSTAGE,BANK,1368316041,1,VAULT,Attacker,DefendersEliminated,142,...,Vertical,None,MuzzleBrake,M45_MEUSOC,Pistols,None,None,Laser,Suppressor,SMOKE_GRENADE
3999998,20170221,PS4,HOSTAGE,BANK,1368316041,4,VAULT,Defender,AttackersEliminated,156,...,Vertical,None,Compensator,P9,Pistols,None,None,None,None,BREACH_CHARGE
3999999,20170221,PS4,HOSTAGE,BANK,1368316041,8,VAULT,Defender,AttackersEliminated,141,...,Angle,None,None,PMM,Pistols,None,None,None,None,NITRO_CELL

In [6]:
df = pd.read_csv('datadump_s5-000.csv')
df = df.drop(['endroundreason','dateid','roundduration','clearancelevel','skillrank','role','team','haswon','nbkills','isdead','primaryweapon','primaryweapontype','primarysight','primarygrip','primaryunderbarrel','primarybarrel','secondaryweapon','secondaryweapontype','secondarysight','secondarygrip','secondaryunderbarrel','secondarybarrel','secondarygadget','platform','matchid'], axis=1, errors='ignore')
df.head()

  gamemode     mapname  roundnumber objectivelocation   winrole      operator
0  HOSTAGE  CLUB_HOUSE            1        STRIP_CLUB  Defender   SWAT-CASTLE
1  HOSTAGE  CLUB_HOUSE            4            CHURCH  Defender    GSG9-JAGER
2  HOSTAGE  CLUB_HOUSE            3            CHURCH  Defender    JTF2-FROST
3  HOSTAGE  CLUB_HOUSE            4            CHURCH  Defender  BOPE-CAVEIRA
4  HOSTAGE  CLUB_HOUSE            6           BEDROOM  Attacker    GSG9-JAGER

In [7]:
df['mapname'].unique()

array(['CLUB_HOUSE', 'PLANE', 'KANAL', 'HEREFORD_BASE', 'CONSULATE',
       'YACHT', 'OREGON', 'BORDER', 'SKYSCRAPER', 'BANK', 'COASTLINE',
       'BARTLETT_U.', 'HOUSE', 'KAFE_DOSTOYEVSKY', 'FAVELAS', 'CHALET'],
      dtype=object)

In [8]:
df.tail()

,gamemode,mapname,roundnumber,objectivelocation,winrole,operator
3999995,HOSTAGE,BANK,6,STAFF_ROOM,Defender,SAT-HIBANA
3999996,HOSTAGE,BANK,2,VAULT,Attacker,SAT-HIBANA
3999997,HOSTAGE,BANK,1,VAULT,Attacker,SWAT-ASH
3999998,HOSTAGE,BANK,4,VAULT,Defender,GIGN-TWITCH
3999999,HOSTAGE,BANK,8,VAULT,Defender,SPETSNAZ-KAPKAN

In [10]:
df.notnull()

,dateid,platform,gamemode,mapname,matchid,roundnumber,objectivelocation,winrole,endroundreason
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
3999995,True,True,True,True,True,True,True,True,True
3999996,True,True,True,True,True,True,True,True,True
3999997,True,True,True,True,True,True,True,True,True
3999998,True,True,True,True,True,True,True,True,True
3999999,True,True,True,True,True,True,True,True,True